defaults: &defaults
  adapter: postgresql
  username: postgres
  password: rakesh
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  database: Teaser-app_development
  <<: *defaults

test:
  database: Teaser-app_test
  <<: *defaults

production:
  database: Teaser-app_production
  <<: *defaults
