# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06c05496d51e7050a6880645bb83e726ad8c47154844f0472994e54ed47d94f42114fc447869472a5dcf67b3dbaa1dad4e74f7424331a8a6bf175f6a9430d71

test:
  secret_key_base: e47d01d937879a1f792894cf0e3055faa4bb40cb78b2172b1e1d2c9d70980c23262a8eeb2da833f2f2a59a2202293137dc57489b213d3d5acc2d810c462b6415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8b17caee2f53ffdca6249c2a7896038e3b6494bc4f593730b16bc1459919ea4cbc8e783e1d79cc887f06b10f53eac70dddacab42dd0708d15377c377091a8888
