twitter:
    name: 'teaser_app'
    consumer_key: 'JkV2KSc6SyqItogUTNU8cDpyT'
    consumer_secret: 'wzesmwKObogs4sPyRcu5WJlcCf62gWRcbeUjG3an3oovMQPj1G'
    oauth_token: '2934163898-xrUYRIZVug9cfbqztsRzz4XmrjIXC6zIJwSmppH'
    oauth_token_secret: '3QUFL1M6ohHkZ2ja7YBiol3KZ4LKSACL3a8brqSsQsS0s'